name: Manage Github Repositories Resources
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      repository_list_path:
        description: 'The repository path of json repositories list'
        required: true
        type: string

      # INSTALL DEPENDENCIES
      # LOGIN BITBUCKET 
      # Login Github
      # Recorrer listado repos
        # Obtener ref repo y clonarlo
        # Crear nuevo repositorio en Github con el mismo nombre
        # Subir contenido clonado en local
      # Correr herramienta migracion bamboo pipelines y analizar o ejecutar
        
jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      
    - name: Get List repositories
      run: |
        curl --request GET \
          --url 'https://api.bitbucket.org/2.0/repositories/noeorgagutierrez' \
          --header 'Authorization: Bearer <access_token>' \ #Falta Token por ser premium feature, un acces key no se si es posible
          --header 'Accept: application/json'

    - name: Create repository in Github
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/orgs/NTTData-IDP/repos \
        -d '{"name":"frontend-angular","description":"This is your frontend-angular repository","homepage":"https://github.com","private":true,"has_issues":true,"has_projects":true,"has_wiki":true,"auto_init":true}'
    
    - name: Clone Bitbucket repository
      run: |
        git clone --mirror https://bitbucket.org/noeorgagutierrez/workspace/projects/LAB/frontend-angular.git
        cd repositorio-bitbucket.git
        git remote set-url --push origin https://github.com/NTTData-IDP/repositorio.git
        git push --mirror
    
